### ISSUE TITLE
Web Interface username/password?

### ISSUE THREAD

**Issue by rodbalgarnie** [charlesquick/ntripcaster-containerised#1]
HI Charles, Thnaks for creating this docker version and was able to get your software up and running without too many headaches..
Does this version have the BKG web interface? I could get the login popup on /admin but can't see where the default userrname/password is defined to login? Also tried via telnet (folliowing the BKG manual) and defining admin_password in the ntripcaster.conf but was getting a 'Unknown setting admin_password' in the log when I restarted the caster.
Regards, Rod

**Comment by charlesquick** [comment]
Hi Rod,
Those features are in the professional version only I think.
You get that login popup at any arbitrary directory you try to access it seems. I don't think it actually checks against any users, it's just an easy way to keep everyone out.

**Comment by rodbalgarnie** [comment]
Thanks , makes sense now, was looking for something that wasn't there.
Regards,
Rod
